
default: &default
    adapter: postgresql
    encoding: unicode
    pool: 5
    host: postgresql://$OPENSHIFT_POSTGRESQL_DB_HOST:$OPENSHIFT_POSTGRESQL_DB_PORT
    database: selfup
    user: adminggkpb75
    port: 5432
    password: gY1tmaur3gaa

development:
 <<: *default

production:
    <<: *default


