
default: &default
 adapter: sqlite3
 pool: 5
 timeout: 5000

development:
 <<: *default
 database: db/development.sqlite3

production:
    adapter: postresql
    encoding: unicode
    pool: 5
    host: ec2-107-22-166-233.compute-1.amazonaws.com
    database: dc9fun1qd8opgh
    user: yivubqzlorjvan
    port: 5432
    password: UNKQ4GdefVICsuuyQsnU4IfkMa



