
default: &default
    adapter: postgresql
    encoding: unicode
    pool: 5
    host: postgresql://$OPENSHIFT_POSTGRESQL_DB_HOST:$OPENSHIFT_POSTGRESQL_DB_PORT
    database: selfup
    user: adminpmkruih
    port: 5432
    password: NQLBTBvshkvw

development:
 <<: *default

production:
    <<: *default


